spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springcloud_sell?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
  application:
    name: product
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  jpa:
    show-sql: true
girl: 18
env:
  dev
